src/atoms/ProviderSelection/ProviderSelection.module.scss, src/atoms/ProviderSelection/ProviderSelection.tsx, src/hostedPages/SchedulingActivity.tsx, src/lib/api/__mocks__/providers.ts, src/lib/api/providers.schema.ts
going to try to add the number of open slots for the provider over the next 7 days. Unknown how the backend will respond to calls where there are 30-40+ providers, so this merge is experimental
=> add slots to provider

package.json, src/PreferencesProvider/PreferencesContext.tsx, src/PreferencesProvider/utils.ts, src/atoms/BookingError/BookingError.tsx, src/atoms/Calendar/week/DayCard.tsx, src/atoms/Calendar/week/WeekCalendar.stories.tsx, src/atoms/Calendar/week/WeekCalendar.tsx, src/atoms/ProviderAvatar/ProviderAvatar.tsx, src/atoms/ProviderAvatar/index.tsx, src/atoms/ProviderSelection/ProviderCard.tsx, src/atoms/ProviderSelection/ProviderFilter/FilterBadge.tsx, src/atoms/ProviderSelection/ProviderFilter/FilterSelector.tsx, src/atoms/ProviderSelection/ProviderSelection.tsx, src/atoms/ProviderSelection/types.ts, src/atoms/Slots/Slots.stories.tsx, src/lib/api/__mocks__/providerAvailability.mock.ts, src/lib/api/__mocks__/providers.mock.ts, src/lib/api/schema/atoms/eventDeliveryMethod.schema.ts, src/lib/api/schema/availabilities.schema.ts, src/lib/api/schema/shared.schema.ts, src/lib/constants.ts, src/molecules/Scheduler/Scheduler.stories.tsx, src/molecules/Scheduler/Scheduler.tsx
=> Improvements

package.json, src/PreferencesProvider/PreferencesContext.tsx, src/SolApiProvider/SolApiContext.tsx, src/atoms/FetchingProvidersError/FetchingProvidersError.stories.tsx, src/atoms/FetchingProvidersError/FetchingProvidersError.tsx, src/atoms/FetchingProvidersError/index.tsx, src/atoms/ProviderSelection/ProviderSelection.tsx, src/atoms/index.tsx
enhancement, bug fix
___
- Added error handling for fetching providers in `PreferencesContext` and `SolApiProvider`.
- Created a new `FetchingProvidersError` component to display error messages when provider fetching fails.
- Integrated the `FetchingProvidersError` component into the `ProviderSelection` component.
- Added a Storybook story for the `FetchingProvidersError` component.
- Updated package version to 0.2.17.
___
<tr>
<td>
<details>
<summary><strong>PreferencesContext.tsx</strong><dd><code>Add error handling to PreferencesContext for provider fetching</code></dd></summary>
<hr>
src/PreferencesProvider/PreferencesContext.tsx
<li>Added …
=> Add error handling when fetching providers fail

package.json, src/atoms/ProviderSelection/ProviderSelection.tsx
The layout now looks off with the error message so updating it
___
enhancement, miscellaneous
___
- Refactored the `ProviderSelection` component to improve the layout and readability by handling loading and error states separately.
- Removed unnecessary import of `isNil` from `lodash-es`.
- Updated the package version in `package.json` from `0.2.17` to `0.2.18`.
___
<tr>
<td>
<details>
<summary><strong>ProviderSelection.tsx</strong><dd><code>Refactor loading and error handling in ProviderSelection component</code></dd></summary>
<hr>
src/atoms/ProviderSelection/ProviderSelection.tsx
<li>Removed the <code>isNil</code> import from …
=> fix layout

package.json, src/PreferencesProvider/utils.ts, src/lib/api/schema/GetProviders.schema.ts
Bug fix, Enhancement
___
- Fixed the location filter logic by ensuring `prefs.location` is set to undefined when necessary to clear the filter.
- Cleaned up the `GetProvidersResponseSchema` by removing unnecessary commented-out code.
- Updated the package version to 0.2.19 in `package.json`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>utils.ts</strong><dd><code>Fix and enhance location filter logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/PreferencesProvider/utils.ts
<li>Added logic to clear the location filter by setting …
=> ET-278-fix-location-filter

package.json, src/atoms/ProviderSelection/ProviderSelection.tsx
Bug fix, Enhancement
___
- Refactored the `ProviderSelection` component to separate loading and error handling into distinct components, improving readability and maintainability.
- Introduced conditional rendering to handle loading states and errors more effectively.
- Updated the package version in `package.json` from 0.2.20 to 0.2.21.
___
<tr>
<td>
<details>
<summary><strong>ProviderSelection.tsx</strong><dd><code>Refactor loading and error handling in ProviderSelection component</code></dd></summary>
<hr>
src/atoms/ProviderSelection/ProviderSelection.tsx
<li>Added <code>isNil</code> import from <code>lodash-es</code>.<br> <li> Refactored loading and …
=> Et 277 fix infinity loading screen

package.json, src/atoms/ProviderSelection/ProviderCard.tsx, src/atoms/ProviderSelection/ProviderFilter/utils.ts, style.css
enhancement, bug fix
___
- Enhanced the `ProviderCard` component by modifying the display format of clinic locations.
- Improved the utility function for enum key extraction by adding logic to handle specific patterns.
- Cleaned up the CSS file by removing unused styles, improving maintainability.
- Updated the package version in `package.json` to reflect changes.
___
<tr>
<td>
<details>
<summary><strong>ProviderCard.tsx</strong><dd><code>Update facility display format in ProviderCard</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/atoms/ProviderSelection/ProviderCard.tsx
<li>Modified the …
=> cosmetic changes to filters

package.json, src/atoms/BookingError/BookingError.stories.tsx, src/atoms/Calendar/week/WeekCalendar.stories.tsx, src/atoms/Slots/Slots.stories.tsx, src/hostedPages/SchedulingActivity.stories.tsx, src/lib/api/__mocks__/GetProviderAvailability.mock.ts, src/lib/api/__mocks__/GetProviders.mock.ts, src/lib/api/schema/atoms/EventDeliveryMethod.schema.ts, src/lib/api/schema/shared.schema.ts, src/lib/utils/availabilities/filters.test.ts, src/lib/utils/availabilities/filters.ts, src/lib/utils/preferences/preparePreferencesForSalesforce.test.ts, src/molecules/Scheduler/Scheduler.stories.tsx
enhancement, configuration changes
___
- Updated various story files to use new mocking dates and provider IDs.
- Introduced mock functions for fetching providers and availability in story files.
- Changed location descriptions from 'virtual only' to 'Telehealth' in mock data.
- Updated `EventDeliveryMethod` enum to reflect new location terminology.
- Bumped package version to 0.3.0 to reflect significant changes.
___
<tr>
<td>
<details>
<summary><strong>WeekCalendar.stories.tsx</strong><dd><code>Update mocking date and provider ID in WeekCalendar stories</code></dd></summary>
<hr>
src/atoms/Calendar/week/WeekCalendar.stories.tsx
<li>Updated the mocking …
=> update location to In-Person or Telehealth

.github/workflows/storybook-interaction-tests.yml, src/atoms/Calendar/week/WeekCalendar.spec.ts, src/atoms/Calendar/week/WeekCalendar.stories.tsx, src/lib/api/schema/atoms/TherapeuticModality.schema.ts, src/molecules/Scheduler/Scheduler.spec.ts
Tests, Enhancement
___
- Updated test dates in `WeekCalendar.spec.ts` and `Scheduler.spec.ts` to October 2024 to ensure tests align with current calendar.
- Adjusted test logic and expectations in `Scheduler.spec.ts` to reflect new slot availability and button interactions.
- Enhanced `TherapeuticModality.schema.ts` by adding a check for empty values using `isEmpty` from lodash-es and modifying transformation logic accordingly.
- Changed mocking date in `WeekCalendar.stories.tsx` to October 14, 2024, to match updated test scenarios.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>WeekCalendar.spec.ts</strong><dd><code>Update test dates and expectations in WeekCalendar …
=> fix(interaction-tests): passing storybook tests

package.json, src/lib/api/schema/atoms/LocationFacility.schema.ts, src/lib/api/schema/atoms/LocationState.schema.ts
enhancement, bug fix
___
- Enhanced `LocationFacilitySchema` and `LocationStateSchema` to accept empty strings, addressing potential issues with invalid location schema.
- Updated the package version to 0.3.4 in `package.json`.
___
<tr>
<td>
<details>
<summary><strong>LocationFacility.schema.ts</strong><dd><code>Allow empty strings in LocationFacilitySchema</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/lib/api/schema/atoms/LocationFacility.schema.ts
<li>Added a union type to accept empty strings in <code>LocationFacilitySchema</code>.<br> <li> Modified the schema to explicitly allow …
=> allow empty strings

package.json, src/atoms/Calendar/week/WeekCalendar.tsx, src/atoms/FetchingProvidersError/FetchingProvidersError.tsx
Enhancement, Bug fix
___
- Enhanced the `FetchingProvidersError` component by adding phone numbers for different states and a copy-to-clipboard feature.
- Refactored the retry button into a separate `RetryButton` component for better code organization.
- Added guidance text in the `WeekCalendar` component to help users select clinic locations.
- Updated the package version in `package.json` from 0.3.7 to 0.3.8.
___
<tr>
<td>
<details>
<summary><strong>WeekCalendar.tsx</strong><dd><code>Add guidance text for clinic location selection</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Tp 2578 ux updates

package.json, src/atoms/ProviderSelection/ProviderFilter/FilterList.tsx
enhancement, configuration changes
___
- Implemented sorting logic for the `FilterList` component to order filters based on a predefined sequence.
- Updated the package version in `package.json` from 0.3.9 to 0.3.10.
___
<tr>
<td>
<details>
<summary><strong>FilterList.tsx</strong><dd><code>Implement sorting logic for filter list</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/atoms/ProviderSelection/ProviderFilter/FilterList.tsx
<li>Added sorting logic for filters based on a predefined order.<br> <li> Introduced a <code>filterOrder</code> array to …
=> ET-304-sort-filter

package.json, src/lib/api/schema/__tests__/GetProviders.schema.test.ts, src/lib/api/schema/atoms/Age.schema.ts
enhancement, tests
___
- Removed the maximum age limit from the age validation schema, allowing for greater flexibility in age input.
- Updated test cases to reflect the removal of the maximum age limit, ensuring tests focus on minimum age validation.
- Incremented the package version to 0.3.13 to reflect these changes.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>GetProviders.schema.test.ts</strong><dd><code>Update age validation tests to remove max age limit</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/lib/api/schema/__tests__/GetProviders.schema.test.ts
<li>Updated test descriptions to reflect removal of max age limit.<br> <li> …
=> remove upper limit on age

docs/api.spec.yaml
documentation
___
- Updated the `AgePreference` schema in the API documentation to reflect a new minimum age value of 5.
- Clarified that there is no maximum age limit for the `AgePreference`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api.spec.yaml</strong><dd><code>Update age validation description in API documentation</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/api.spec.yaml
<li>Updated the description of the <code>AgePreference</code> schema.<br> <li> Changed the minimum age value from 6 to 5.<br> <li> Clarified that there is no maximum age limit.<br>
</details>
</td>
<td><a href="https://github.com/awell-health/sol-scheduling/pull/58/files#di …
=> chore(docs): update age validation

docs/api.spec.yaml
Closes https://github.com/awell-health/sol-scheduling/issues/61
___
- Updated the production server URL in the API specification file `api.spec.yaml`.
- Changed the domain for the production environment from `azurewebsites.net` to `solmentalhealth.com`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>api.spec.yaml</strong><dd><code>Update production server URL in API specification</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
docs/api.spec.yaml
<li>Updated the production server URL.<br> <li> Changed domain from <code>azurewebsites.net</code> to <code>solmentalhealth.com</code>.<br>
</details>
</td>
<td><a …
=> chore(docs): new prod URL

package.json, src/atoms/Calendar/week/WeekCalendar.tsx
___
bug_fix, enhancement
___
- Fixed the display logic for location options in the `WeekCalendar` component to ensure 'Telehealth' is displayed fully, while other options are sliced.
- Updated the package version in `package.json` from 0.3.15 to 0.3.16.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Bug fix</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>WeekCalendar.tsx</strong><dd><code>Fix location option display logic in WeekCalendar</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/atoms/Calendar/week/WeekCalendar.tsx
<li>Modified the display logic for location options.<br> <li> Ensured 'Telehealth' is displayed fully, others are sliced.<br>
</details>
</td>
<td><a …
=> fix-facility-label

package.json, src/SolApiProvider/SolApiContext.tsx, src/hostedPages/SchedulingActivity.stories.tsx, src/hostedPages/SchedulingActivityWithoutProviderSelection.stories.tsx, src/lib/api/__mocks__/GetProviderAvailability.mock.ts, src/molecules/Scheduler/__mocks__/scheduler.mocks.ts
enhancement, bug fix
___
- Improved error logging in `SolApiProvider` by including the error object in the console output.
- Updated storybook files to replace mock functions with `fn()` and added comments for debugging.
- Modified mock provider availability response to use dynamic dates, enhancing test reliability.
- Bumped package version to 0.3.17 to reflect the changes.
___
<tr>
<td>
<details>
<summary><strong>SolApiContext.tsx</strong><dd><code>Improve error logging in SolApiProvider</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> chore(): minor improvements

src/atoms/Calendar/week/WeekCalendar.spec.ts, src/atoms/Calendar/week/WeekCalendar.tsx
enhancement, tests
___
- Updated the week calendar component to disable navigation to past weeks by modifying the condition for disabling the 'prevWeekButton'.
- Enhanced test cases to verify that the 'prevWeekButton' is correctly disabled when attempting to navigate to past weeks.
- Removed redundant test code and adjusted existing tests to align with the new navigation logic.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>WeekCalendar.spec.ts</strong><dd><code>Update tests for week navigation disabling logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/atoms/Calendar/week/WeekCalendar.spec.ts
<li>Added checks to …
=> ET-421: Weekcalendar - disable going to the past

src/atoms/ProviderSelection/ProviderCard.tsx, src/molecules/Scheduler/Scheduler.tsx
I have bumped the avatar size with 50% and ~30% on the provider search and booking page, respectively.
___
- Enhanced the layout of the `ProviderCard` component to be more responsive and increased the avatar size to 24x24.
- Improved the `Scheduler` component by making its layout responsive and enlarging the avatar size to 32x32, with responsive adjustments for different screen sizes.
- Adjusted element alignments and order for better visual presentation in both components.
___
<tr>
<td>
<details>
<summary><strong>ProviderCard.tsx</strong><dd><code>Enhance ProviderCard layout and increase avatar size</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
=> ET-419: increase avatar size

package.json, src/atoms/ProviderSelection/ProviderFilter/FilterBadge.tsx, src/atoms/ProviderSelection/ProviderFilter/ProviderFilter.tsx
enhancement, other
___
- Improved the display of filter badges by adjusting the maximum width for multi-select filters and refining class definitions for better alignment.
- Simplified the provider filter layout by removing unused imports and styles, and adjusting the container layout.
- Updated the package version in `package.json` from 0.3.20 to 0.3.21.
___
<tr>
<td>
<details>
<summary><strong>FilterBadge.tsx</strong><dd><code>Improve filter badge display and alignment</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> Et 424 show all filters on small screen

package.json, src/atoms/AvailabilitySlots/AvailabilitySlot.stories.tsx, src/atoms/AvailabilitySlots/AvailabilitySlot.tsx, src/atoms/AvailabilitySlots/AvailabilitySlots.stories.tsx, src/atoms/AvailabilitySlots/AvailabilitySlots.tsx, src/atoms/AvailabilitySlots/index.tsx, src/atoms/Calendar/week/WeekCalendar.tsx, src/atoms/ProviderSelection/ProviderCard.tsx, src/atoms/index.tsx, src/molecules/Scheduler/Scheduler.spec.ts, src/molecules/Scheduler/Scheduler.tsx
-add next available slots
-fix layour on small screen
-small UI improvements
https://www.loom.com/share/82b51d02ebb14562ba9a4b71ef0820bf
___
enhancement, tests
___
- Implemented new `AvailabilitySlot` and `AvailabilitySlots` components to display available time slots.
- Added stories for `AvailabilitySlot` and `AvailabilitySlots` components to Storybook with theme configuration.
- Refactored `ProviderCard` to include `AvailabilitySlots` and improved layout and styling.
- Updated button styling in `WeekCalendar` for better responsiveness.
- Bumped package version to 0.3.22.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td>
<details> …
=> Et 454 show next available slots

package.json, src/atoms/AvailabilitySlots/AvailabilitySlots.tsx, src/atoms/ProviderSelection/ProviderCard.tsx, style.css
Enhancement, Bug fix
___
- Redesign provider card layout with avatar column
- Simplify bio and facility display items
- Remove static availability label text
- Update utility CSS: add border, padding; remove unused sizes
___
```mermaid
flowchart LR
ProviderCard["ProviderCard layout refactor"] -- "move avatar to left column" --> Avatar["ProviderAvatar usage"]
ProviderCard -- "split content; add divider" --> Layout["Flex layout + border"]
ProviderCard -- "simplify items" --> Items["SingleItem/BioItem props update"]
Availability["AvailabilitySlots label logic"] -- "remove static 'Next Availability:'" --> Label["Conditional empty label"]
CSS["CSS utilities update"] -- "add .sol-border, .sol-p-1" --> Utilities["New utilities"]
CSS -- "remove unused sizes/classes" --> Cleanup["Prune w-32/h-32, …
```
=> HTD-SOL-1.1 Provider Cards

package.json, src/atoms/Calendar/week/WeekCalendar.spec.ts, src/atoms/Calendar/week/WeekCalendar.stories.tsx, src/atoms/Calendar/week/WeekCalendar.tsx, src/atoms/Calendar/week/atoms/DayCard.tsx, src/atoms/Slots/Slots.tsx, src/lib/api/__mocks__/GetProviderAvailability.mock.ts, style.css
Enhancement, Bug fix, Tests
___
- Refactor WeekCalendar to sliding 5-day view
- Simplify props, remove week/weekend logic
- Improve DayCard layout and slot labeling
- Extend mocks and update styles/utilities
___
```mermaid
flowchart LR
WeekCalendar["WeekCalendar.tsx"]
DayCard["week/atoms/DayCard.tsx"]
Slots["Slots.tsx"]
Mocks["__mocks__/GetProviderAvailability.mock.ts"]
Stories["WeekCalendar.stories.tsx"]
Styles["style.css"]
Package["package.json"]
WeekCalendar -- "use availableDates, 5-day slice" --> DayCard
WeekCalendar -- "prev/next index nav" --> DayCard
WeekCalendar -- "auto-select first available" --> DayCard
DayCard -- "layout, responsive slot count" --> Styles
Slots -- "consistent height, class order" --> Styles
Stories -- "remove unused props" --> WeekCalendar
Mocks -- "more days …
```
=> HTD-SOL [2.3] Improve calendar display logic

package.json, src/atoms/Calendar/week/WeekCalendar.tsx
Enhancement
___
- Filter out disabled and empty dates
- Reorder available dates computation
- Streamline days generation slice-map flow
- Reset pagination on availability change
___
```mermaid
flowchart LR
avail["Availabilities"] --> uniq["Unique date strings (yyyy-MM-dd)"]
uniq --> parse["Parse to Date and sort"]
parse --> filter["Filter: not disabled AND has slots"]
filter --> availDates["availableDates"]
availDates -- "slice(currentStartIndex, +5)" --> genDays["Map to day objects"]
```
<tr>
<td>
<details>
<summary><strong>WeekCalendar.tsx</strong><dd><code>Filter and streamline availableDates and …
=> HTD-SOL Fix timezone calendar filters

package.json, style.css, styles/globals.css
- Enhancement
___
- Improve avatar image rendering behavior
- Switch object-fit from cover to fill
- Bump package version to 0.4.9
___
```mermaid
flowchart LR
css["Update avatar CSS object-fit"] -- "cover -> fill" --> ui["Avatar rendering behavior"]
pkg["package.json version"] -- "0.4.8 -> 0.4.9" --> release["New package release"]
```
<tr>
<td>
<details>
<summary><strong>style.css</strong><dd><code>Avatar images now use object-fit: fill</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> HTD-SOL [1.4] fix avatars resolution

docs/api.spec.yaml, package.json, src/PreferencesProvider/utils.ts, src/atoms/ProviderSelection/ProviderSelection.spec.ts, src/atoms/ProviderSelection/types.ts, src/lib/api/schema/GetProviders.schema.ts, src/lib/api/schema/atoms/Insurance.schema.ts, src/lib/api/schema/atoms/Language.schema.ts, src/lib/api/schema/atoms/TimeOfTheDay.schema.ts, src/lib/api/schema/atoms/index.ts
Enhancement, Documentation
___
- Add time-of-day filter and schema
- Integrate therapeutic modality mapping
- Update provider input schema and types
- Document API with new preference
___
```mermaid
flowchart LR
enums["Add TimeOfTheDay enum/schema"]
api["Extend GetProvidersInputSchema"]
utilsUpd["Update preferences utils"]
typesUpd["Expand FilterEnum types"]
docs["Update OpenAPI spec"]
enums -- "export + transform" --> api
api -- "accept timeOfTheDay" --> utilsUpd
utilsUpd -- "map filters <-> prefs" --> api
typesUpd -- "include TimeOfTheDay" --> utilsUpd
utilsUpd -- "modality mapping logic" --> api
api -- "document preferences" --> docs
```
<table><thead><tr><th></th><th align="left">Relevant …
=> HTD-SOL Time of the Day and Therapeutic Modality filters

docs/api.spec.yaml, package.json, src/PreferencesProvider/utils.ts, src/atoms/AvailabilitySlots/AvailabilitySlots.tsx, src/atoms/Calendar/week/atoms/DayCard.tsx, src/atoms/ProviderSelection/ProviderCard.tsx, src/atoms/ProviderSelection/ProviderFilter/FilterList.tsx, src/atoms/ProviderSelection/ProviderSelection.spec.ts, src/atoms/ProviderSelection/types.ts, src/atoms/Slots/Slots.tsx, src/lib/api/schema/atoms/Insurance.schema.ts, src/molecules/Scheduler/Scheduler.tsx, style.css
Enhancement
___
- Improve mobile responsiveness across components
- Adjust typography and visibility for small screens
- Refine slots and provider card layouts
- Extend utility CSS with new responsive classes
___
```mermaid
flowchart LR
Providers["ProviderCard layout and text tweaks"] -- "mobile-first layout" --> Mobile["Small screens improvements"]
Calendar["DayCard typography & month visibility"] -- "optimize small screens" --> Mobile
Slots["Slots card height & icon placement"] -- "responsive spacing/text" --> Mobile
CSS["Utility classes in style.css"] -- "new width/grid/text helpers" --> Components["Atoms using new classes"]
Package["package.json version bump"] -- "0.4.12" --> Release["Publish patch"]
``` …
=> HTD-SOL Enhance component styles for better responsiveness

package.json, src/atoms/Calendar/week/NavigationButton.tsx, style.css
Enhancement, Bug fix
___
- Fix button padding class for consistency
- Bump package version to 0.4.13
___
```mermaid
flowchart LR
NavBtn["Update NavigationButton classes"] -- "ensure consistent padding" --> UI["Consistent UI styling"]
Version["Bump version to 0.4.13"] -- "publish change" --> Release["New package release"]
```
<tr>
<td>
<details>
<summary><strong>NavigationButton.tsx</strong><dd><code>Align NavigationButton padding classes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
=> HTD-SOL Bump version to 0.4.13 and adjust button class for consistency

package.json, src/molecules/Scheduler/Scheduler.tsx, style.css
Bug fix, Enhancement
___
- Remove location-based slot filtering
- Keep date-based availability filtering
- Simplify Scheduler slot selection logic
- Bump package version to 0.4.16
___
```mermaid
flowchart LR
Scheduler["Scheduler.tsx"]
AvailUtils["availabilities utils"]
Styles["style.css"]
Package["package.json"]
Scheduler -- "stop using filterByLocation" --> AvailUtils
Scheduler -- "use filterByDate only" --> AvailUtils
Styles -- "remove sm:grid-cols-3 utility" --> Styles
Package -- "version 0.4.16" --> Package
```
<tr>
<td>
<details>
<summary><strong>Scheduler.tsx</strong><dd><code>Simplify …
=> HTD SOL Scheduler bug fix

docs/api.spec.yaml, package.json, src/lib/api/schema/atoms/LocationFacility.schema.ts
Enhancement, Documentation
___
- Correct DC/VA location codes in enum
- Sync OpenAPI spec with updated locations
- Bump package version to 0.4.18
___
```mermaid
flowchart LR
enum["LocationFacility enum"] -- "update MD Downtown -> DC" --> code["Codebase consistency"]
spec["OpenAPI spec (docs/api.spec.yaml)"] -- "reflect DC/VA codes" --> docs["Documentation consistency"]
version["package.json version 0.4.18"] -- "publish change" --> release["Release"]
code -- "mirrors enum" --> spec
```
<tr>
<td>
<details>
<summary><strong>LocationFacility.schema.ts</strong><dd><code>Fix `Downtown` enum value to …
=> Update location facility enum values for consistency

package.json, src/atoms/Calendar/week/WeekCalendar.tsx, src/molecules/Scheduler/__mocks__/scheduler.mocks.ts
Bug fix, Enhancement, Tests
___
- Fix timezone-safe available dates calculation
- Show month from selected date
- Update scheduler mock data and fields
- Bump package version to 0.4.19
___
```mermaid
flowchart LR
dates["Available dates collection"]
dayStart["Use startOfDay per slot"]
uniqSort["Unique, sorted, filtered dates"]
header["Header month display"]
selected["Use selectedDate for month"]
mocks["Scheduler mocks updated"]
version["Version bump 0.4.19"]
dates -- "map slotstart by yyyy-MM-dd" --> dayStart
dayStart -- "collect Map values" --> uniqSort
uniqSort -- "drives days rendering" --> header
selected -- "format(MMMM yyyy)" --> header
mocks -- "new 2025 sample data" --> uniqSort
version -- "publish change" --> header
``` …
=> HTD SOL timezone date bug
